name: jisho_example
description: Demonstrates how to use the jisho plugin.
publish_to: "none"

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  jisho:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - packages/jisho/index/080d0121166f4c8e98bf4fb0d90b272f.fieldnorm
    - packages/jisho/index/.tantivy-meta.lock
    - packages/jisho/index/1c2b8aa1fb5b4ede95f3df7d70f8db2c.posidx
    - packages/jisho/index/080d0121166f4c8e98bf4fb0d90b272f.pos
    - packages/jisho/index/84f0f68190f249ba825ddac8fcff2547.fast
    - packages/jisho/index/1c2b8aa1fb5b4ede95f3df7d70f8db2c.fast
    - packages/jisho/index/1c2b8aa1fb5b4ede95f3df7d70f8db2c.pos
    - packages/jisho/index/1c2b8aa1fb5b4ede95f3df7d70f8db2c.idx
    - packages/jisho/index/1c2b8aa1fb5b4ede95f3df7d70f8db2c.term
    - packages/jisho/index/.managed.json
    - packages/jisho/index/84f0f68190f249ba825ddac8fcff2547.store
    - packages/jisho/index/080d0121166f4c8e98bf4fb0d90b272f.posidx
    - packages/jisho/index/84f0f68190f249ba825ddac8fcff2547.fieldnorm
    - packages/jisho/index/84f0f68190f249ba825ddac8fcff2547.idx
    - packages/jisho/index/meta.json
    - packages/jisho/index/1c2b8aa1fb5b4ede95f3df7d70f8db2c.store
    - packages/jisho/index/84f0f68190f249ba825ddac8fcff2547.term
    - packages/jisho/index/1c2b8aa1fb5b4ede95f3df7d70f8db2c.fieldnorm
    - packages/jisho/index/.tantivy-writer.lock
    - packages/jisho/index/080d0121166f4c8e98bf4fb0d90b272f.term
    - packages/jisho/index/84f0f68190f249ba825ddac8fcff2547.posidx
    - packages/jisho/index/84f0f68190f249ba825ddac8fcff2547.pos
    - packages/jisho/index/080d0121166f4c8e98bf4fb0d90b272f.idx
    - packages/jisho/index/080d0121166f4c8e98bf4fb0d90b272f.fast
    - packages/jisho/index/080d0121166f4c8e98bf4fb0d90b272f.store
