name: jisho
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The androidPackage and pluginClass identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    androidPackage: com.example.jisho
    pluginClass: JishoPlugin
  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - lib/index/080d0121166f4c8e98bf4fb0d90b272f.fieldnorm
    - lib/index/.tantivy-meta.lock
    - lib/index/1c2b8aa1fb5b4ede95f3df7d70f8db2c.posidx
    - lib/index/080d0121166f4c8e98bf4fb0d90b272f.pos
    - lib/index/84f0f68190f249ba825ddac8fcff2547.fast
    - lib/index/1c2b8aa1fb5b4ede95f3df7d70f8db2c.fast
    - lib/index/1c2b8aa1fb5b4ede95f3df7d70f8db2c.pos
    - lib/index/1c2b8aa1fb5b4ede95f3df7d70f8db2c.idx
    - lib/index/1c2b8aa1fb5b4ede95f3df7d70f8db2c.term
    - lib/index/.managed.json
    - lib/index/84f0f68190f249ba825ddac8fcff2547.store
    - lib/index/080d0121166f4c8e98bf4fb0d90b272f.posidx
    - lib/index/84f0f68190f249ba825ddac8fcff2547.fieldnorm
    - lib/index/84f0f68190f249ba825ddac8fcff2547.idx
    - lib/index/meta.json
    - lib/index/1c2b8aa1fb5b4ede95f3df7d70f8db2c.store
    - lib/index/84f0f68190f249ba825ddac8fcff2547.term
    - lib/index/1c2b8aa1fb5b4ede95f3df7d70f8db2c.fieldnorm
    - lib/index/.tantivy-writer.lock
    - lib/index/080d0121166f4c8e98bf4fb0d90b272f.term
    - lib/index/84f0f68190f249ba825ddac8fcff2547.posidx
    - lib/index/84f0f68190f249ba825ddac8fcff2547.pos
    - lib/index/080d0121166f4c8e98bf4fb0d90b272f.idx
    - lib/index/080d0121166f4c8e98bf4fb0d90b272f.fast
    - lib/index/080d0121166f4c8e98bf4fb0d90b272f.store
  #
  # For details regarding assets in packages, see
  # https://flutter.dev-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev-and-images/#resolution-aware.
  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
